// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-contact-details.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/data.ts
var studio = {
  name: "Ceylance",
  tagline: "AI-native product development studio",
  summary: "Ceylance is a software consulting and product development studio. We help small and medium businesses ship software, mobile apps, websites, AI assistants and workflow automation \u2014 embedding with the team instead of handing over specs.",
  markets: ["Australia", "United Kingdom", "United Arab Emirates"],
  website: "https://ceylance.com",
  differentiators: [
    "Embedded senior team, not an outsourced ticket queue",
    "Plain-English scoping \u2014 you don't need to speak developer",
    "Weekly shipping cycles with tight feedback loops",
    "Agile delivery with transparent communication",
    "Post-launch support and continuous optimisation"
  ]
};
var contact = {
  email: "hello@ceylance.com",
  phone: "+61 404 173 536",
  baseCity: "Adelaide, Australia",
  responseTime: "Within 24 hours",
  brochure: "https://ceylance.com/ceylance-brochure.pdf"
};
var packages = [
  {
    outcome: "Take my idea to launch",
    bestFor: "New founders, non-technical owners with an app idea",
    includes: "Scope, design, build, launch and handover",
    timeline: "6\u201312 weeks"
  },
  {
    outcome: "Build a mobile app",
    bestFor: "Businesses that need a customer-facing iOS or Android app",
    includes: "Native-quality mobile app, App Store listing",
    timeline: "8\u201314 weeks"
  },
  {
    outcome: "A website that grows the business",
    bestFor: "Service businesses, coaches, clinics and trades",
    includes: "Conversion-focused site, CMS and booking/contact flow",
    timeline: "3\u20138 weeks"
  },
  {
    outcome: "Put AI to work in your business",
    bestFor: "Teams drowning in documents, search or repetitive queries",
    includes: "AI assistant, document processing or search workflow",
    timeline: "4\u201310 weeks"
  },
  {
    outcome: "Automate the repetitive stuff",
    bestFor: "Businesses manually copying data between tools",
    includes: "Workflow integration, auto quotes, invoices and reports",
    timeline: "3\u20138 weeks"
  },
  {
    outcome: "Modernise a tired system",
    bestFor: "Companies stuck on old software or spreadsheets",
    includes: "Refactor/rebuild to a fast, secure, cloud-based system",
    timeline: "8\u201316 weeks"
  }
];
var caseStudies = [
  {
    industry: "Healthcare",
    title: "Remote Patient Monitoring App for Elderly Care",
    summary: "Developed the patient-facing mobile app for Dignio, a Norwegian remote-care specialist. The cloud-based platform enables healthcare providers to monitor patients remotely via telehealth, RPM and preventive medicine \u2014 now serving the UK and USA markets.",
    results: ["Award-winning platform", "3 international markets", "Improved patient independence"]
  },
  {
    industry: "EdTech",
    title: "AI-Powered Interactive STEM Learning Platform",
    summary: "Built AI-driven features for zyBooks, an interactive textbook platform replacing traditional STEM coursework. The system personalises learning paths and provides real-time feedback to boost student confidence and outcomes.",
    results: ["Adopted by major universities", "Higher completion rates", "Reduced instructor workload"]
  },
  {
    industry: "Veterinary",
    title: "Practice Management System for Vet Clinics",
    summary: "Engineered the core practice management software for Vetserve, a Norwegian IT provider serving animal clinics and hospitals. The platform was later acquired by Provet, a leading international veterinary software group.",
    results: ["Successful acquisition", "Clinics & hospitals served", "Streamlined operations"]
  },
  {
    industry: "SaaS / PR",
    title: "PR Workflow & Source Management Platform",
    summary: "Built PR Monkey, a Public Relations SaaS that lets professionals upload sources, pitch journalists and track performance, with insights into where clients need attention.",
    results: ["End-to-end PR workflow", "Real-time pitch tracking", "Free beta launch"]
  },
  {
    industry: "FinTech / Identity",
    title: "Digital Identity Wallet for SMEs",
    summary: "Developed Oliu Wallet for ATB Ventures \u2014 a ready-to-deploy digital identity management platform enabling SMEs to verify credentials securely and adopt decentralised identity.",
    results: ["Enterprise-grade security", "SME-ready deployment", "Decentralised identity"]
  },
  {
    industry: "Finance / AI",
    title: "AI-Driven Equity Analysis Engine",
    summary: "Built an intelligent equity analysis platform that uses machine learning to parse financial data, identify market patterns and generate actionable investment insights for portfolio managers.",
    results: ["Automated analysis pipeline", "Real-time market signals", "Data-driven decisions"]
  }
];
var processSteps = [
  {
    num: "01",
    title: "Schedule your call",
    desc: "A quick, honest conversation \u2014 no pitch decks. We learn your product, your goals, and where AI can move the needle fastest."
  },
  {
    num: "02",
    title: "Scope the engagement",
    desc: "Pick a plan that fits where you are today. No lock-in, no long contracts \u2014 we earn your trust sprint over sprint."
  },
  {
    num: "03",
    title: "We ship in iterations",
    desc: "We embed, prioritise and start moving fast. Weekly cycles, tight feedback loops, real output \u2014 not status reports."
  },
  {
    num: "04",
    title: "Compound & scale",
    desc: "The longer we're in, the sharper we get. Every cycle we understand your product deeper and raise the bar on what we ship."
  }
];

// src/lib/mcp/tools/get-contact-details.ts
var get_contact_details_default = defineTool({
  name: "get_contact_details",
  title: "Get contact details",
  description: "Get Ceylance's public contact details: email, phone, base city, expected response time and the company brochure link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: { contact }
  })
});

// src/lib/mcp/tools/get-studio-overview.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_studio_overview_default = defineTool2({
  name: "get_studio_overview",
  title: "Get studio overview",
  description: "Get a summary of Ceylance: what the studio does, the markets it serves and what makes its delivery model different.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(studio, null, 2) }],
    structuredContent: { studio }
  })
});

// src/lib/mcp/tools/list-case-studies.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_case_studies_default = defineTool3({
  name: "list_case_studies",
  title: "List case studies",
  description: "List Ceylance case studies with the industry, project summary and outcomes. Optionally filter by industry keyword (e.g. healthcare, fintech, edtech).",
  inputSchema: {
    industry: z.string().trim().min(1).optional().describe("Optional industry keyword to filter case studies by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ industry }) => {
    const needle = industry?.toLowerCase();
    const items = needle ? caseStudies.filter(
      (s) => s.industry.toLowerCase().includes(needle) || s.title.toLowerCase().includes(needle) || s.summary.toLowerCase().includes(needle)
    ) : [...caseStudies];
    if (items.length === 0) {
      return {
        content: [
          {
            type: "text",
            text: `No case studies matched "${industry}". Known industries: ${caseStudies.map((s) => s.industry).join(", ")}.`
          }
        ],
        structuredContent: { items: [] }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/list-process-steps.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_process_steps_default = defineTool4({
  name: "list_process_steps",
  title: "List engagement process",
  description: "List the four steps of how a Ceylance engagement runs, from first call to ongoing scale.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(processSteps, null, 2) }],
    structuredContent: { steps: processSteps }
  })
});

// src/lib/mcp/tools/list-service-packages.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_service_packages_default = defineTool5({
  name: "list_service_packages",
  title: "List service packages",
  description: "List Ceylance's service packages by business outcome, including who each is best for, what is included and the typical delivery timeline.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(packages, null, 2) }],
    structuredContent: { packages }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ceylance-studio",
  title: "Ceylance Studio",
  version: "0.1.0",
  instructions: "Public tools describing Ceylance, an AI-native product development studio. Use `get_studio_overview` for what the studio does, `list_service_packages` for engagement options and timelines, `list_case_studies` for past work (optionally filtered by industry), `list_process_steps` for how an engagement runs, and `get_contact_details` to reach the team.",
  tools: [get_studio_overview_default, list_service_packages_default, list_case_studies_default, list_process_steps_default, get_contact_details_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
